### ISSUE TITLE
Fix eraser 

### ISSUE THREAD

**Issue by lowisgo** [drewguiao/DrawMeDaddy#42]
Nageerase lang kapag solo player. Hindi nabobroadcast yung pag erase

**Comment by drewguiao** [comment]
what you can try:
1. get the background color nung drawingArea, then use it as brush color. (e.g white yung background, so parang brush lang din siya pero mukhang nag-eerase hahaha). No addtl code needed for broadcasting kasi meron na kung sakaling ganito gagawin mo. :)

**Comment by drewguiao** [comment]
also, hindi nagbbroadcast talaga kapag example, nagset ka sa server na 2 lang yung players. Kung isa pa lang na nagddrawing, hindi mabbroadcast unless kumpleto na sila
